FROM node:8.9-alpine as node-angular-cli
LABEL authors="Jerome Jourdon"

# Building angular app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app

# Creating bundle
RUN npm run build -- --prod

WORKDIR /app/dist
EXPOSE 80
ENV PORT 80
RUN npm install http-server -g
CMD ["http-server"]
