FROM node:8.9-alpine as node-angular-cli
LABEL authors="Jerome Jourdon"

# Building angular app
WORKDIR /app
COPY package.json /app
RUN npm install
COPY . /app

# Creating bundle
RUN npm run build -- --prod

# This image will be used for the container
FROM node:8.9-alpine
WORKDIR /app
# Copying the dist folder from node-angular-cli image
COPY --from=node-angular-cli /app/dist .
EXPOSE 80
ENV PORT 80
RUN npm install http-server -g
CMD ["http-server"]
